spring:
  application:
    name: millie-backend
  datasource:
    url: jdbc:postgresql://localhost:5432/mydb
    username: kt
    password: kt123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc.time_zone: Asia/Seoul
    show-sql: false

  flyway:
    enabled: false

server:
  port: 8080

logging:
  level:
    org.hibernate.SQL: debug
